version: '3.8'  

services:
  db:
    container_name: notes_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Giraffe#LemonTree88!
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
  app:
    container_name: note_widget
    build: ./
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:@note_db:5432/note_db
    depends_on:
      - db
  redis:
    container_name: redis_for_notes
    image: redis:7