"""add title to note model

Revision ID: 7047d2891734
Revises: 796f96cf4f13
Create Date: 2024-09-19 13:59:36.185156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7047d2891734'
down_revision: Union[str, None] = '796f96cf4f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
